version: "3"
# Named volumes
volumes:
  # Mongodb Data
  techmainda-mongo:
    driver: local

services:
  api:
    image: ambientum/node:lts
    container_name: techmainda-node
    command: npm run dev
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    links:
      - mongodb

  mongodb:
    container_name: techmainda-mongo
    restart: on-failure
    image: bitnami/mongodb:3.6
    ports:
      - "27017:27017"
    volumes:
      - techmainda-mongo:/data/db
    environment:
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=my_database
