version: "3"
# Named volumes
volumes:
  # Mongodb Data
  carenet-mongo:
    driver: local

services:
  api:
    image: ambientum/node:lts
    container_name: carenet-node
    command: npm run dev
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    links:
      - mongodb

  mongodb:
    container_name: carenet-mongo
    restart: on-failure
    image: bitnami/mongodb:3.6
    ports:
      - "27017:27017"
    volumes:
      - carenet-mongo:/data/db
    environment:
      - MONGODB_USERNAME=carenet
      - MONGODB_PASSWORD=carenet@mongo
      - MONGODB_DATABASE=carenet
